### ISSUE TITLE
Title doesn't show for a long lyrics

### ISSUE THREAD

**Issue by madebyaris** [aviwad/SpotifyLyricsInMenubar#10]
I found a new issue in here:
<img width="804" alt="image" src="https://github.com/aviwad/SpotifyLyricsInMenubar/assets/13942122/7631cf0c-2fc4-447e-aa90-73d4d6ace1bd">
So, if the lyrics it's too long, it will not appear.

I think it will be hard to do the code where the lyrics isn't timestamp per word :D 

Anyway, on the tiktok Music it can appear like this, the lyrics will be slowly moving to left (I didn't use if because the sound quality isn't great for me)
<img width="825" alt="image" src="https://github.com/aviwad/SpotifyLyricsInMenubar/assets/13942122/cda668cb-ec0d-475d-816d-0e567dc58ec4">

**Comment by aviwad** [comment]
1. I have set a 50 character limit on the lyrics... maybe i can set an option for lyric length limits
2. what app is this? tiktok music? can you send a link? have never used this before.

**Comment by aviwad** [comment]
Hey. Just released version V1.6 that lets you set custom truncation length :D Hope that helps !! Closing this for now.

**Comment by madebyaris** [comment]
Thank You, I will test it, and menyala abangku 🔥🔥🔥🔥🔥 (meaning in English: Great Job)
